replicaCount: 1

image:
  repository: networkstatic/iperf3
  tag: "latest"
  pullPolicy: IfNotPresent

args:
  - "-s"

containerPort: 5201

service:
  type: ClusterIP
  port: 5201
  annotations:
    tailscale.com/expose: "true"

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

resources: {}
